config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :tweets do
    member do
      put 'like', to: "tweets#like"
      put 'unlike', to: "tweets#unlike"
    end
  end
  root 'tweets#index'
  get '/profile/:id' => 'tweets#profile', as: 'profile'
  post '/following/:id' => 'following#create', as: 'follow'
  delete 'following/:id' => 'following#destroy', as: 'unfollow'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/following.rb
class Following < ApplicationRecord
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  acts_as_votable
  belongs_to :user
end

app/models/uploadable.rb
class Uploadable < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_voter
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets, dependent: :destroy
  has_one_attached :avatar, dependent: :destroy
  has_many :followings, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/following_controller.rb
class FollowingController < ApplicationController

  def create
    @following = current_user.followings.build
    @following.following = params[:id]
    if @following.save
      redirect_back fallback_location: root_path
    else
      redirect_to '/failed'
    end
  end

  def destroy
    @following = Following.find_by(following: params[:id], user_id: current_user.id)
    @following.destroy
    redirect_back fallback_location: root_path
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :avatar, :bio, :avatar_shot)
  end

  def account_update_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password, :avatar, :bio, :avatar_shot)
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy, :like, :unlike]
  before_action :authenticate_user!, except: [:index, :show, :like]

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all.order("created_at DESC")
    @tweet = Tweet.new
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = current_user.tweets.build
    session[:id] = true
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = current_user.tweets.build(tweet_params)

    respond_to do |format|
      if @tweet.save
        if session[:id]
          session[:id] = false
          format.html { redirect_to tweet_path(@tweet), notice: 'Tweet was successfully created.' }
        else
          format.html { redirect_back fallback_location: root_path, notice: 'Tweet was successfully created.' }
        end
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def like
    @tweet.liked_by current_user
    respond_to do |format|
      format.html { redirect_back fallback_location: root_path }
      format.js { render layout: false }
    end
  end

  def unlike
    @tweet.unliked_by current_user
    respond_to do |format|
      format.html { redirect_back fallback_location: root_path }
      format.js { render layout: false }
    end
  end

  def profile
    @user = User.find_by(username: params[:id])
    @followings = Following.where(user_id: current_user.id).pluck('following')
    @tweets = @user.tweets.order("created_at DESC")
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:tweet)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/following_helper.rb
module FollowingHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTwitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <style media="screen">
      /* We don't need checkbox to be displayed in order for it to work */
      .toggler {
        display: none;
      }

      /* Below are all the functionalities */

      /* Hamburger changes to X when toggler is checked */
      .navbar .toggler:checked + .navbar-brand .burger span:nth-child(1) {
        -webkit-transform: translateY(5px) rotate(45deg);
        transform: translateY(5px) rotate(45deg);
      }
      .navbar .toggler:checked + .navbar-brand .burger span:nth-child(2) {
        opacity: 0;
      }
      .navbar .toggler:checked + .navbar-brand .burger span:nth-child(3) {
        -webkit-transform: translateY(-5px) rotate(-45deg);
        transform: translateY(-5px) rotate(-45deg);
      }

      /*  Displays menu when toggler is checked only on mobile/tablet */
      @media screen and (max-width: 1024px) {
        .navbar .toggler:checked ~ .navbar-menu {
          display: block;
        }
        /* We don't want menu to be displayed on mobile by default */
        .navbar-menu {
          display: none;
        }
      }
    </style>
  </head>

  <body>
    <section class="hero is-info is-medium">
        <div class="hero-head">
          <nav class="navbar" role="navigation" aria-label="main navigation">
            <div class="container">
              <input type="checkbox" id="toggler" class="toggler" />
              <div class="navbar-brand">
                <%= link_to root_path do %>
                  <div class="navbar-item" style="color:white;">
                    <i class="fa fa-twitter fa-4x" aria-hidden="true"></i>
                    <p class="title is-5"> Clone</p>
                  </div>
                <% end %>
                <label for="toggler" role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
                  <span aria-hidden="true"></span>
                  <span aria-hidden="true"></span>
                  <span aria-hidden="true"></span>
                </label>
              </div>
              <div id="navbarBasicExample" class="navbar-menu" >
                <div class="navbar-end">

                  <div class="field is-grouped">
                    <% if user_signed_in? %>
                      <%= link_to current_user.name, profile_path(current_user.username), class: "control navbar-item", style: "color:white;"%>
                      <a href="/tweets/new" class="control navbar-item"><button class="button is-info is-inverted">New Tweet</button></a>
                      <%= link_to destroy_user_session_path, class: "control navbar-item", method: :delete, data: {confirm: "Are you sure?"} do %>
                        <button class="button is-danger">Logout</button>
                      <% end %>
                    <% else %>
                      <%= link_to "Sign up", new_user_registration_path, class: "control navbar-item", style: "color:white;"%>
                      <%= link_to "Sign in", new_user_session_path, class: "control navbar-item", style: "color:white;"%>
                    <% end %>
                  </div>

                </div><!-- end navbar-start-->
              </div>
          </nav>
          <% if flash[:notice] %>
            <div class="notification is-primary global-notification">
              <p class="notice"><%= notice %></p>
            </div>
          <% end %>
          <% if flash[:alert] %>
            <div class="notification is-danger global-notification">
              <p class="alert"><%= alert %></p>
            </div>
          <% end %>
        </div>
      </section>
    <%= yield %>
  </body>
</html>

app/views/tweets/_feed.html.erb
<div class="column is-9">
  <% if user_signed_in? %>
    <article class="media box">
      <figure class="media-left">
        <p class="image is-64x64">
          <% if current_user.avatar_shot!='' && Uploadable.count==0 %>
            <image src="<%= current_user.avatar_shot %>" alt="">
          <% elsif current_user.avatar.attached? %>
            <%= image_tag current_user.avatar, size: '64x64' %>
          <% else %>
            <img src="https://bulma.io/images/placeholders/64x64.png">
          <% end %>
        </p>
      </figure>
      <div class="media-content">
        <%= render 'tweets/form' %>
      </div>
    </article>
  <% end %>

<% @tweets.each do |tweet| %>
  <div class="box">
    <article class="media">
      <div class="media-left">
        <figure class="media-left">
          <p class="image is-64x64">
            <% if tweet.user.avatar_shot!='' && Uploadable.count==0 %>
              <image src="<%= tweet.user.avatar_shot %>" alt="">
            <% elsif tweet.user.avatar.attached? %>
              <%= image_tag tweet.user.avatar, size: '64x64' %>
            <% else %>
              <img src="https://bulma.io/images/placeholders/64x64.png">
            <% end %>
          </p>
        </figure>
      </div>
      <div class="media-content">
        <div class="content">
          <a href="<%= profile_path(tweet.user.username) %>"><strong><%= tweet.user.name %></strong><br/></a>
          <small><%= tweet.user.username %></small><br/><br>
          <p><%= tweet.tweet %></p>
          <p><small><em><%= time_ago_in_words(tweet.created_at) %> ago</em></small></p>
        </div>
        <% if user_signed_in? %>
          <nav class="level">
            <div class="level-left likes data">
              <div class="votes">
               <% if user_signed_in? %>
                  <% if current_user.liked? tweet %>
                    <%= link_to unlike_tweet_path(tweet), method: :put, class: 'unlike_tweet' do %>
                        <span class="icon"><i class="fa fa-heart has-text-primary"></i></span>
                        <span class="vote_count"><%= tweet.get_likes.size %></span>
                    <% end %>
                  <% else %>
                    <%= link_to like_tweet_path(tweet), method: :put, class: 'like_tweet' do %>
                      <span class="icon"><i class="fa fa-heart"></i></span>
                      <span class="vote_count"><%= tweet.get_likes.size %></span>
                    <% end %>
                  <% end %>
                <% else %>
                    <%= link_to like_tweet_path(tweet), method: :put, class: 'like_tweet' do %>
                      <span class="icon"><i class="fa fa-heart"></i></span>
                      <span class="vote_count"><%= tweet.get_likes.size %></span>
                    <% end %>
                <% end %>
              </div>
            </div>
            <div class="level-right">
              <% if user_signed_in? %>
                <%= link_to tweet_path(tweet), class: 'level-item' do %>
                  <span class="icon">
                    <i class="fa fa-link" aria-hidden='true'></i>
                  </span>
                <% end %>
                <%if current_user.id == tweet.user_id %>
                  <%= link_to edit_tweet_path(tweet), class: 'level-item' do %>
                    <span class="icon">
                      <i class="fa fa-pencil" aria-hidden='true'></i>
                    </span>
                  <% end %>
                <%= link_to tweet, class: 'level-item', method: :delete, data: {confirm: "Are you sure you want to delete this tweet"} do %>
                  <span class="icon">
                    <i class="fa fa-trash" aria-hidden='true'></i>
                  </span>
                <% end %>
              <% end %>
            </div>
          </nav>
          <% end %>
        <% end %>
      </div>
    </article>
  </div>
<% end %>
</div>

app/views/tweets/_form.html.erb
<%= simple_form_for(@tweet) do |f| %>
  <%= f.error_notification %>
  <div class="field">
    <div class="control">
      <%= f.input :tweet, label: "Tweet about it", input_html: {class: 'textarea'}, wrapper: false,label_html: {class: 'label'}, placeholder: 'Compose a new tweet...', required: true, maxlength: 500 %>
    </div>
  </div>
  <div class="field">
    <%= f.button :submit, class: 'button is-info' %>
  </div>
<% end %>

app/views/tweets/_login.html.erb
<div class="column is-9">
  <div class="box">
    <h2 class="title is-2">Log In</h2>
    <%= simple_form_for(resource, url: new_user_session_path(resource)) do |f| %>
      <%= f.error_notification %>

        <div class="field">
          <div class="control">
            <%= f.input :email,
                        required: true,
                        autofocus: true,
                        input_html: { class: "input" },
                        wrapper: false,
                        label_html: {class: "label"}%>
          </div>
        </div>

        <div class="field">
          <div class="control">
            <%= f.input :password,
                        required: true,
                        hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length),
                        input_html: { class: "input" },
                        wrapper: false,
                        label_html: {class: "label"} %>
          </div>
        </div>
        <div class="field">
          <div class="control">
                    <%= f.check_box :remember_me,
                                    input_html: { class: "input" },
                                    wrapper: false,
                                    label_html: {class: "label"},
                                    hint: ("remember me")%>
            Remember me
          </div>
        </div>

        <div class="field">
          <div class="control">
            <%= f.button :submit, "Sign in", class: "button is-info is-medium" %>
          </div>
        </div>

    <% end %>
    <br />
    Don't have an account,
    <%= link_to 'Sign up', '/users/sign_up' %> instead<br>
    <%= link_to 'Forgot your password?', '/users/password/new' %>
  </div>
</div>

app/views/tweets/_profile.html.erb
<div class="column is-4">
  <nav class="panel">
    <p class="panel-heading">Profile</p>
    <div class="panel-block">
      <article class="media">
        <div class="media-left">
          <figure class="media-left">
            <p class="image is-64x64">
              <% if current_user.avatar_shot!='' && Uploadable.count==0 %>
                <image src="<%= current_user.avatar_shot %>" alt="">
              <% elsif current_user.avatar.attached? %>
                <%= image_tag current_user.avatar, size: '64x64' %>
              <% else %>
                <img src="https://bulma.io/images/placeholders/64x64.png">
              <% end %>
            </p>
          </figure>
        </div>
        <div class="media-content">
          <div class="content ">
            <p>
              <a href="<%= profile_path(current_user.username) %>"><strong><%= current_user.name %></strong></a><br>
              <small><%= current_user.username %><br>
              <%= (current_user.bio) %></small>
            </p>
          </div>
        </div>
      </article>
    </div>
    <div class="panel-block">
      <div class="level is-mobile">
        <div class="level-item has-centered-text">
          <div>
            <p class="heading">Tweets</p>
            <p class="title is-6"><%= current_user.tweets.count %></p>
          </div>
        </div>
        <div class="level-item has-centered-text">
          <div>
            <p class="heading">Following</p>
            <p class="title is-6"><%= Following.where(user_id: current_user.id).count %></p>
          </div>
        </div>
        <div class="level-item has-centered-text">
          <div>
            <p class="heading">Followers</p>
            <p class="title is-6"><%= Following.where(following: current_user.id).count %></p>
          </div>
        </div>
      </div>
    </div>
  </nav>
  <% if user_signed_in? %>
  <nav class="panel">
    <p class="panel-heading">Who to Follow</p>
    <% temp = User.pluck(:id) - ( [] << current_user.id ) - ( Following.where(user_id: current_user.id).pluck(:following) ) %>
    <% temp.each do |u| %>
        <% user = User.find(u) %>
        <div class="panel-block">
          <article class="media">
            <div class="media-left">
              <figure class="media-left">
                <p class="image is-64x64">
                  <% if user.avatar_shot!='' && Uploadable.count==0 %>
                    <image src="<%= user.avatar_shot %>" alt="">
                  <% elsif user.avatar.attached? %>
                    <%= image_tag user.avatar, size: '64x64' %>
                  <% else %>
                    <img src="https://bulma.io/images/placeholders/64x64.png">
                  <% end %>
                </p>
              </figure>
            </div>
            <div class="media-content">
              <div class="content">
                <p>
                  <strong>
                    <%= link_to profile_path(user.username) do %>
                      <%= user.name %>
                    <% end %>
                  </strong><br/>
                  <small>@<%= user.username %></small>
                </p>
              </div>
            </div>
          </article>
        </div>
    <% end %>
  </nav>
  <% end %>
</div>

app/views/tweets/_trends.html.erb
<div class="column is-3">
  <!-- <nav class="panel">
    <p class="panel-heading">Trends</p>
    <a href="#" class="panel-block">Trend 1</a>
    <a href="#" class="panel-block">Trend 2</a>
    <a href="#" class="panel-block">Trend 3</a>
    <a href="#" class="panel-block">Trend 4</a>
    <a href="#" class="panel-block">Trend 5</a>
  </nav> -->
  <nav class="panel">
    <p class="panel-heading">Who to Follow</p>
    <% User.order(Arel.sql('RANDOM()')).each do |user| %>
        <div class="panel-block">
          <article class="media">
            <div class="media-left">
              <figure class="media-left">
                <p class="image is-64x64">
                  <% if user.avatar_shot!='' && Uploadable.count==0 %>
                    <image src="<%= user.avatar_shot %>" alt="">
                  <% elsif user.avatar.attached? %>
                    <%= image_tag user.avatar, size: '64x64' %>
                  <% else %>
                    <img src="https://bulma.io/images/placeholders/64x64.png">
                  <% end %>
                </p>
              </figure>
            </div>
            <div class="media-content">
              <div class="content">
                <p>
                  <strong><%= user.name %></strong><br/>
                  <small>@<%= user.username %></small>
                </p>
              </div>
            </div>
          </article>
        </div>
    <% end %>
  </nav>
</div>

app/views/tweets/edit.html.erb
<div class="column is-three-fifths is-offset-one-fifth">
  <article class="media box">
    <figure class="media-left">
      <p class="image is-64x64">
        <% if current_user.avatar_shot!='' && Uploadable.count==0 %>
          <image src="<%= current_user.avatar_shot %>" alt="">
        <% elsif current_user.avatar.attached? %>
          <%= image_tag current_user.avatar, size: '64x64' %>
        <% else %>
          <img src="https://bulma.io/images/placeholders/64x64.png">
        <% end %>
      </p>
    </figure>
    <div class="media-content">
      <%= render 'tweets/form' %>

    </div>
  </article>
  <div class="field">
    <%= link_to root_path do %>
      <button class="button is-info">Back</button>
    <% end %>
  </div>
</div>

app/views/tweets/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
        <% if user_signed_in? || (!user_signed_in? and Tweet.count!=0) %>
          <%= render 'feed' %>
        <% else %>
          <%= render 'login', resource: User.new %>
        <% end %>
        <% if user_signed_in? %>
          <%= render 'profile' %>
        <% else %>
          <%= render 'trends' %>
        <% end %>
    </div>
  </div>
</section>

app/views/tweets/new.html.erb
<div class="column is-three-fifths is-offset-one-fifth">
  <article class="media box">
    <figure class="media-left">
      <p class="image is-64x64">
        <% if current_user.avatar_shot!='' && Uploadable.count==0 %>
          <image src="<%= @tweet.user.avatar_shot %>" alt="">
        <% elsif current_user.avatar.attached? %>
          <image src="<%= url_for(current_user.avatar) %>">
        <% else %>
          <img src="https://bulma.io/images/placeholders/64x64.png">
        <% end %>
      </p>
    </figure>
    <div class="media-content">
      <%= render 'tweets/form' %>

    </div>
  </article>
  <div class="field">
    <%= link_to root_path do %>
      <button class="button is-info">Home</button>
    <% end %>
  </div>
</div>

app/views/tweets/profile.html.erb
<div class="column  is-half is-offset-one-fifth">
  <nav class="panel">
    <div class="panel-block">
      <article class="media">
        <div class="media-left">
          <figure class="media-left">
            <p class="image is-128x128">
              <% if @user.avatar_shot!='' && Uploadable.count==0 %>
                <image src="<%= @user.avatar_shot %>" alt="">
              <% elsif @user.avatar.attached? %>
                <image src="<%= url_for(@user.avatar) %>">
              <% else %>
                <img src="https://bulma.io/images/placeholders/64x64.png">
              <% end %>
            </p>
          </figure>
        </div>
        <div class="media-content">
          <div class="content has-text-justified">
            <p>
              <strong><%= @user.name %></strong><br>
              <small><%= @user.username %></small><br>
              <%= @user.bio %><br>
              <% unless @user.id == current_user.id %>
                <% if @user.id.in?(@followings) %>
                  <%= link_to 'Unfollow', unfollow_path(@user), method: :delete %>
                <% else %>
                  <%= link_to 'Follow', follow_path(@user), method: :post %>
                <% end %>
              <% else %>
                  <%= link_to 'Edit Profile', edit_user_registration_path(current_user) %>
              <% end %>
            </p>
          </div>
        </div>
      </article>
    </div>
    <div class="panel-block">
      <div class="level is-mobile">
        <div class="level-item has-centered-text">
          <div>
            <p class="heading">Tweets</p>
            <p class="title is-6"><%= @user.tweets.count %></p>
          </div>
        </div>
        <div class="level-item has-centered-text">
          <div>
            <p class="heading">Following</p>
            <p class="title is-6"><%= Following.where(user_id: @user.id).count %></p>
          </div>
        </div>
        <div class="level-item has-centered-text">
          <div>
            <p class="heading">Followers</p>
            <p class="title is-6"><%= Following.where(following: @user.id).count %></p>
          </div>
        </div>
      </div>
    </div>
  </nav>

  <% @tweets.each do |tweet| %>
    <div class="box">
      <article class="media">
        <div class="media-left">
          <figure class="media-left">
            <p class="image is-64x64">
              <% if tweet.user.avatar_shot!='' && Uploadable.count==0 %>
                <image src="<%= tweet.user.avatar_shot %>" alt="">
              <% elsif tweet.user.avatar.attached? %>
                <%= image_tag tweet.user.avatar, size: '64x64' %>
              <% else %>
                <img src="https://bulma.io/images/placeholders/64x64.png">
              <% end %>
            </p>
          </figure>
        </div>
        <div class="media-content">
          <div class="content">
            <a href="<%= profile_path(tweet.user.username) %>"><strong><%= tweet.user.name %></strong><br/></a>
            <small><%= tweet.user.username %></small><br/><br>
            <p><%= tweet.tweet %></p>
            <p><small><em><%= time_ago_in_words(tweet.created_at) %> ago</em></small></p>
          </div>
          <% if user_signed_in? %>
            <% if current_user.id == tweet.user_id %>
            <nav class="level">

                <div class="level-left likes data">
                  <div class="votes">
                   <% if user_signed_in? %>
                      <% if current_user.liked? tweet %>
                        <%= link_to unlike_tweet_path(tweet), method: :put, class: 'unlike_tweet' do %>
                            <span class="icon"><i class="fa fa-heart has-text-primary"></i></span>
                            <span class="vote_count"><%= tweet.get_likes.size %></span>
                        <% end %>
                      <% else %>
                        <%= link_to like_tweet_path(tweet), method: :put, class: 'like_tweet' do %>
                          <span class="icon"><i class="fa fa-heart"></i></span>
                          <span class="vote_count"><%= tweet.get_likes.size %></span>
                        <% end %>
                      <% end %>
                    <% else %>
                        <%= link_to like_tweet_path(tweet), method: :put, class: 'like_tweet' do %>
                          <span class="icon"><i class="fa fa-heart"></i></span>
                          <span class="vote_count"><%= tweet.get_likes.size %></span>
                        <% end %>
                    <% end %>
                  </div>
                </div>

                <div class="level-right">
                  <%= link_to tweet, class: 'level-item' do %>
                    <span class="icon">
                      <i class="fa fa-link" aria-hidden='true'></i>
                    </span>
                  <% end %>
                  <%= link_to edit_tweet_path(tweet), class: 'level-item' do %>
                    <span class="icon">
                      <i class="fa fa-pencil" aria-hidden='true'></i>
                    </span>
                  <% end %>
                  <%= link_to tweet, class: 'level-item', method: :delete, data: {confirm: "Are you sure you want to delete this tweet"} do %>
                    <span class="icon">
                      <i class="fa fa-trash" aria-hidden='true'></i>
                    </span>
                  <% end %>
                </div>

            </nav>
            <% end %>
          <% end %>
        </div>
      </article>
    </div>
  <% end %>

</div>

app/views/tweets/show.html.erb
<div class="column  is-half is-offset-one-fifth">
  <div class="box">
    <article class="media">
      <div class="media-left">
        <figure class="media-left">
          <p class="image is-64x64">
            <% if @tweet.user.avatar_shot!='' && Uploadable.count==0 %>
              <image src="<%= @tweet.user.avatar_shot %>" alt="">
            <% elsif @tweet.user.avatar.attached? %>
              <%= image_tag @tweet.user.avatar, size: '64x64' %>
            <% else %>
              <img src="https://bulma.io/images/placeholders/64x64.png">
            <% end %>
          </p>
        </figure>
      </div>
      <div class="media-content">
        <div class="content">
          <a href="<%= profile_path(@tweet.user.username) %>"><strong><%= @tweet.user.name %></strong><br/></a>
          <small><%= @tweet.user.username %></small><br/><br>
          <p><%= @tweet.tweet %></p>
          <p><small><em><%= time_ago_in_words(@tweet.created_at) %> ago</em></small></p>
        </div>
        <% if user_signed_in? %>
          <nav class="level">
              <div class="level-left likes data">
                <% if user_signed_in? %>
                  <% if current_user.liked? @tweet %>
                    <%= link_to unlike_tweet_path(@tweet), method: :put, class: "unlike_tweet" do %>
                      <span class="icon"><i class="fa fa-heart has-text-primary"></i></span>
                      <span class="vote_count"><%= pluralize(@tweet.get_likes.size, 'Like') %></span>
                    <% end %>
                  <% else %>
                    <%= link_to like_tweet_path(@tweet), method: :put, class: "like_tweet" do %>
                      <span class="icon"><i class="fa fa-heart"></i></span>
                      <span class="vote_count"><%= pluralize(@tweet.get_likes.size, 'Like') %></span>
                    <% end %>
                  <% end %>
                <% else %>
                    <%= link_to like_tweet_path(@tweet), method: :put, class: "like_tweet" do %>
                      <span class="icon"><i class="fa fa-heart"></i></span>
                      <span class="vote_count"><%= pluralize(@tweet.get_likes.size, 'Like') %></span>
                    <% end %>
                <% end %>
              </div>
              <div class="level-right">
                <% if user_signed_in? && current_user.id == @tweet.user_id %>
                <%= link_to edit_tweet_path(@tweet), class: 'level-item' do %>
                  <span class="icon">
                    <i class="fa fa-pencil" aria-hidden='true'></i>
                  </span>
                <% end %>
                <%= link_to @tweet, class: 'level-item', method: :delete, data: {confirm: "Are you sure you want to delete this tweet"} do %>
                  <span class="icon">
                    <i class="fa fa-trash" aria-hidden='true'></i>
                  </span>
                <% end %>
              </div>
          </nav>
          <% end %>
        <% end %>
      </div>
    </article>
  </div>
</div>